# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "20efaa416064887fd36bcfafe1178078"
name = "my-app-facturadora-b1"
handle = "my-app-facturadora-b1"
application_url = "https://yukon-press-issues-touch.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-10820af5.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://yukon-press-issues-touch.trycloudflare.com/auth/callback",
  "https://yukon-press-issues-touch.trycloudflare.com/auth/shopify/callback",
  "https://yukon-press-issues-touch.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
